### PR TITLE
Test: pre-event exercises

### PR DESCRIPTION
**Pull request by LazarIliev**

### CODE REVIEW

**Comment by LazarIliev** [comment]
@vjuge these are the pre-event exercises. We will make review and merge them later.

**Comment by vjuge** [comment]
@LazarIliev 👍 great job, definitively useful. I will check them !
I am delighted to have them so I won't have to implement myself 😄  
do you have other PR in the backlog of that kind ?

**Comment by vjuge** [comment]
Hi,

i've launched the tests, and get following errors : 

```
➜   ./gradlew clean build test
[...]
> Task :cbdc-bridge:test

com.cbdc.industria.tech.bridge.CommercialBankServiceTests > make account deposit() FAILED
    org.opentest4j.AssertionFailedError at CommercialBankServiceTests.kt:223

com.cbdc.industria.tech.bridge.SandboxEnvServiceTests > post environment() FAILED
    org.opentest4j.AssertionFailedError at SandboxEnvServiceTests.kt:33

com.cbdc.industria.tech.bridge.PIPServiceTests > deposit and withdrawal balance to account() FAILED
    com.cbdc.industria.tech.bridge.exceptions.CBDCBridgeException

com.cbdc.industria.tech.bridge.PIPServiceTests > getPips() FAILED
    com.cbdc.industria.tech.bridge.exceptions.CBDCBridgeException

com.cbdc.industria.tech.bridge.PIPServiceTests > createPIP() FAILED
    com.cbdc.industria.tech.bridge.exceptions.CBDCBridgeException

com.cbdc.industria.tech.bridge.PIPServiceTests > registerPartyWithPIP() FAILED
    com.cbdc.industria.tech.bridge.exceptions.CBDCBridgeException

com.cbdc.industria.tech.bridge.PIPServiceTests > executionError FAILED
    com.cbdc.industria.tech.bridge.exceptions.CBDCBridgeException

18 tests completed, 7 failed

> Task :cbdc-bridge:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cbdc-bridge:test'.
> There were failing tests. See the report at: file:///Users/vincentjuge/devel/barclays-cbdc-hackathon/CBDC-Bridge/cbdc-bridge/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 35s
26 actionable tasks: 25 executed, 1 up-to-date
```


my config:

```
➜   ./gradlew -version

------------------------------------------------------------
Gradle 5.6.4
------------------------------------------------------------

Build time:   2019-11-01 20:42:00 UTC
Revision:     dd870424f9bd8e195d614dc14bb140f43c22da98

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_345 (Temurin 25.345-b01)
OS:           Mac OS X 10.16 x86_64

➜   java -version
openjdk version "1.8.0_345"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (Temurin)(build 25.345-b01, mixed mode)


➜   echo $BARCLAYS_AUTH_TOKEN
TEAM020_6UHQ6beoSSUEaJpLgMmlsjvs*********************************
```

Does they require a specific setup on APIs / Env ?
thx.

**Comment by LazarIliev** [comment]
@vjuge  Your setup should be fine. Be sure that you are using your test auth token. The problem with the tests are the following:
the first one is trying to delete an account with non-zero balance. The second one is related to the environment count. Maybe you have more envs as we have. There was a problem on their side which we had reported and we are stuck to delete one env. For that in the PR in which I will ping you in a minute I will change the assert from equal to `1` to not equal to `0`. Because in our case we will always have 2 envs. One that we create in this second test and the one which we can not delete. The others should work. We will continue the discussion in the other PR.

**Pull request merged**
